### PR TITLE
Corrected typings for openQuickCreate, attribute.setIsValid methods and AddNotificationObject.

### LINKED ISSUE #179: Xrm.Utility.openQuickCreate incorrect arguments
I am trying to use Xrm.Utility.openQuickCreate, but the interface is incorrectly defined in the d.ts. I am targeting v 8.2. This method does not accept the callback as the first argument. instead it is using a .then(success, error) approach. Also, in the success callback, it returns an object with a property called savedEntityReference, which contains the Lookup that was created.

**INCORRECT DEFINITION:**

openQuickCreate(_**callback: (lookup: Lookup) => any**_, entityLogicalName: string, createFromEntity?: Lookup, parameters?: any): void;

**CORRECT DEFINITION** (see https://docs.microsoft.com/en-us/previous-versions/dynamicscrm-2016/developers-guide/jj602956(v%3dcrm.8)#openquickcreate)

openQuickCreate(entityLogicalName: string, createFromEntity?: Lookup, parameters?: any)**_.then(successCallback?: (lookup: Lookup) => void, errorCallback?: ErrorCallback): void;_**

### PR DESCRIPTION
**Pull request by sergeytunnik**
Closes #179, #183, #184.

### CODE REVIEW

File: src/XrmDefinitelyTyped/Resources/Extensions/xrm_ext_9-.d.ts [hunk 1]
```diff
@@ -1227,7 +1227,7 @@ declare namespace Xrm {
     }
 
     interface AddNotificationObject {
-        actions?: actionsObject | null;
+        actions?: actionsObject[] | null;
```
Comment (magesoe) [inline src/XrmDefinitelyTyped/Resources/Extensions/xrm_ext_9-.d.ts]: Is the null needed? The argument is already optional. The same applies to the actionsObject typing. I know that is how it was, but we might aswell fix it now :)

Comment (sergeytunnik) [reply src/XrmDefinitelyTyped/Resources/Extensions/xrm_ext_9-.d.ts]: Checked and there is no need to specify nulls for optionals in typescript. Also done smoke checking that actual addNotification method doesn't throw when actions or messages are not specified.

**Comment by TomMalow** [comment]
I believe that the move from callbacks functions to .then() started in 8.2. But I highly doubt that .then() works version below 8.2. The related issue #179 also only mention 8.2.
Until we know if it is also an issue in older version, then I made the choice of splitting the old definition and new definition out to target different version of CRM.

Old definition: Added in 7, removed in 8.2
New definition: Added in 8.2, deprecated in 9.
